<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageVersion Include="MassTransit" Version="9.1.0" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="9.1.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.54.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.6" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2" />
    <PackageVersion Include="Nito.AsyncEx" Version="5.1.2" />
  </ItemGroup>
</Project>